---
- hosts: all
  vars:
    local_docker_dir:       "../sdcc-docker"
    local_git_keypair_dir:  "../sdcc-go-github-keypair" # for development
    local_ssh_scripts_dir:  "../sdcc-ssh"               # for development
    local_app_dir:          "../sdcc-go"
    remote_home:            "/home/admin"
    remote_docker_dir:      "{{remote_home}}/sdcc-docker"
    remote_git_keypair_dir: "{{remote_docker_dir}}/sdcc-go-github-keypair" # for development
    remote_ssh_scripts_dir: "{{remote_docker_dir}}/sdcc-ssh"               # for development
    remote_app_dir:         "{{remote_docker_dir}}/sdcc-go"

  tasks:
#    - name: copy application directory
#      copy:
#        src: "{{ local_app_dir }}/"
#        dest: "{{ remote_app_dir }}"
#      register: app  # save task output 

    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes
 
    - name: Update all packages to their latest version
      become: yes
      apt:
        upgrade: full

    - name: install needed packages
      become: yes # we need root privileges 
      apt:
        name: 
          - docker-compose
          - python3
          - python3-docker
          - python3-pip
          - rsync
        state: present

    - name: pip pip3 alias # in out distribution pip points to pip version 2 instead of 3 as we need
      become: yes
      community.general.alternatives:
        link: /usr/bin/pip
        path: /usr/bin/pip3
        name: pip
        state: present

    - name: python python3 alias # same as before, python points to python version 2 instead of 3
      become: yes
      community.general.alternatives:
        link: /usr/bin/python
        path: /usr/bin/python3
        name: python
        state: present


#    - name: install docker-compose python module
#      become: yes
#      pip:
#        name: 
#          - docker-compose
#        state: present

    - name: sync dockefile # more or less like copy but faster
      synchronize:
        src: "{{ local_docker_dir }}/"
        dest: "{{ remote_docker_dir }}"

    - name: sync github keys # for development
      synchronize:
        src: "{{ local_git_keypair_dir }}/"
        dest: "{{ remote_git_keypair_dir }}"

    - name: sync go app
      synchronize:
        src: "{{ local_app_dir }}/"
        dest: "{{ remote_app_dir }}"

    - name: sync ssh scripts
      synchronize:
        src: "{{ local_ssh_scripts_dir }}/"
        dest: "{{ remote_ssh_scripts_dir }}"

    - name: copy default profile # bash profile for the new non-root user, by default there's only the root user
      copy:
        src: "/etc/skel"
        dest: "{{ remote_docker_dir }}/skel"
        remote_src: "yes"

    - name: make dockefiles # reducer, mapper and master share a base dockefile. make will create the actual dockerfiles merging the base dockefile with the respective ones
      make:
        chdir: "{{remote_docker_dir}}"
        target: all

    - name: docker-compose up # starting docker-compose
      become: yes
      community.docker.docker_compose:
        project_src: "{{remote_docker_dir}}"
        state: present


