---
- hosts: all
  vars:
    local_docker_dir:       "../sdcc-docker"
    local_git_keypair_dir:  "../sdcc-go-github-keypair" # for development
    local_ssh_scripts_dir:  "../sdcc-ssh"               # for development
    local_app_dir:          "../sdcc-go"
    remote_home:            "/home/admin"
    remote_docker_dir:      "{{remote_home}}/sdcc-docker"
    remote_git_keypair_dir: "{{remote_docker_dir}}/sdcc-go-github-keypair" # for development
    remote_ssh_scripts_dir: "{{remote_docker_dir}}/sdcc-ssh"          # for development
    remote_app_dir:         "{{remote_docker_dir}}/sdcc-go"

  tasks:
#    - name: copy application directory
#      copy:
#        src: "{{ local_app_dir }}/"
#        dest: "{{ remote_app_dir }}"
#      register: app  # save task output 

    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes
 
    - name: Update all packages to their latest version
      become: yes
      apt:
        upgrade: full

    - name: install needed packages
      become: yes # we need root privileges 
      apt:
        name: 
          - docker-compose
          - python3
          - python3-docker
          - python3-pip
          - rsync
        state: present

    - name: pip pip3 alias
      become: yes
      community.general.alternatives:
        link: /usr/bin/pip
        path: /usr/bin/pip3
        name: pip
        state: present

    - name: python python3 alias
      become: yes
      community.general.alternatives:
        link: /usr/bin/python
        path: /usr/bin/python3
        name: python
        state: present


#    - name: install docker-compose python module
#      become: yes
#      pip:
#        name: 
#          - docker-compose
#        state: present

    - name: sync dockefile
      synchronize:
        src: "{{ local_docker_dir }}/"
        dest: "{{ remote_docker_dir }}"
#      register: docker  # save task output 

    - name: sync github keys
      synchronize:
        src: "{{ local_git_keypair_dir }}/"
        dest: "{{ remote_git_keypair_dir }}"
#      register: git_kaypair  # save task output 

    - name: sync go app
      synchronize:
        src: "{{ local_app_dir }}/"
        dest: "{{ remote_app_dir }}"
#      register: go_app  # save task output 

    - name: sync ssh scripts
      synchronize:
        src: "{{ local_ssh_scripts_dir }}/"
        dest: "{{ remote_ssh_scripts_dir }}"
#      register: go_app  # save task output 

    - name: copy default profile
      copy:
        src: "/etc/skel"
        dest: "{{ remote_docker_dir }}/skel"
        remote_src: "yes"
#      register: go_app  # save task output 

    - name: make dockefiles
      make:
        chdir: "{{remote_docker_dir}}"
        target: all

    - name: docker-compose up
      become: yes
      community.docker.docker_compose:
        project_src: "{{remote_docker_dir}}"
        state: present


#    - name: install Flask
#      become: yes 
#      pip:
#        name: flask
#        executable: pip3

#    - name: install boto3
#      become: yes 
#      pip:
#        name: boto3
#        executable: pip3

#    - name: copy systemd unit file
#      become: yes 
#      copy:
#        src: "photogallery.service"
#        dest: "/etc/systemd/system/"

#    - name: enable and start systemd service
#      become: yes 
#      systemd:
#        daemon_reload: yes
#        state: restarted
#        name: "photogallery.service"
#        enabled: yes
#      when: app.changed # only restart if new version was uploaded







